import canonicalLaneMathlib.AdmissibleClass
import MedicineSocialEpidemiologyTheoremCanonicalLaneLean.CompartmentModel
import MedicineSocialEpidemiologyTheoremCanonicalLaneLean.PharmacokineticModel
import MedicineSocialEpidemiologyTheoremCanonicalLaneLean.DiagnosticInference
import MedicineSocialEpidemiologyTheoremCanonicalLaneLean.SurvivalAnalysis
import MedicineSocialEpidemiologyTheoremCanonicalLaneLean.SocialDeterminants
import MedicineSocialEpidemiologyTheoremCanonicalLaneLean.FinalTheorem

namespace HautevilleHouse
namespace MedicineSocialEpidemiologyTheoremCanonicalLaneLean

-- This is the root module for the Medicine Social Epidemiology Theorem repository.

end MedicineSocialEpidemiologyTheoremCanonicalLaneLean
end HautevilleHouse